# Generated by Django 5.1.1 on 2024-09-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100, unique=True)),
                ('descricao_produto', models.TextField(default='...')),
                ('categoria_produto', models.CharField(default='', max_length=100)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_produto', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('genero', models.CharField(default='N', max_length=50)),
                ('idade', models.IntegerField(default=0)),
                ('senha', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_compra', models.PositiveIntegerField()),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('produto_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.produto')),
                ('user_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.user')),
            ],
        ),
    ]
