# Generated by Django 5.1.1 on 2024-09-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_produto_imagem_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria_produto',
            field=models.CharField(default='eletronico', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_produto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
