# Generated by Django 5.1.1 on 2024-09-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_alter_produto_categoria_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque_produto',
            field=models.PositiveIntegerField(),
        ),
    ]
