# Generated by Django 5.1.1 on 2024-09-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_alter_produto_estoque_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_produto',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
